# Generated by Django 6.0.4 on 2026-04-30 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceParking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('statut', models.CharField(choices=[('libre', 'Libre'), ('reservee', 'Réservée'), ('occupee', 'Occupée')], default='libre', max_length=10)),
                ('etage', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_debut', models.DateTimeField()),
                ('heure_fin', models.DateTimeField()),
                ('heure_entree_reelle', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('active', 'Active'), ('expiree', 'Expirée'), ('annulee', 'Annulée'), ('terminee', 'Terminée')], default='en_attente', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parking.placeparking')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='JournalAcces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaque_detectee', models.CharField(max_length=20)),
                ('type_evenement', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie'), ('refuse', 'Refusé')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('score_confiance', models.FloatField(default=0.0)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.reservation')),
            ],
        ),
    ]
