# Generated by Django 6.0.4 on 2026-05-08 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalacces',
            options={'ordering': ['-timestamp'], 'verbose_name': "Journal d'accès", 'verbose_name_plural': 'Journal des accès'},
        ),
        migrations.AlterModelOptions(
            name='placeparking',
            options={'ordering': ['numero'], 'verbose_name': 'Place de parking', 'verbose_name_plural': 'Places de parking'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Réservation'},
        ),
    ]
